### ISSUE TITLE
Bug en el put de evento , a la hora de cargar evidencias 

### ISSUE THREAD

**Issue by fran1999** [CERTUNLP/ngen#103]
Cuando se agrega un nuevo elemento a la lista de evidencias, o cuando se manda una lista de evidencias vacía no se reflejan los cambios en el backend.
Ejemplo de eliminación de todas las evidencias:
![image](https://github.com/CERTUNLP/ngen/assets/62036079/c8157380-dcf3-4f19-93e8-1d11b12d22e2)
![image](https://github.com/CERTUNLP/ngen/assets/62036079/48cbc661-10ad-4554-ba86-022fe54d10d4)

**Comment by mateodurante** [comment]
Por diseño se definió que `evidence` es una lista no modificable a través de la api en ese modo, sino que para modificarlo se debe enviar un post http multipart con files, y el backend extrae estos files para agregarlos al caso/evento como evidencias, ignorando la variable evidences del request json.

Esto es así por restricciones de diseño, las cuales con bastantes pruebas y trabajo se podría forzar a que sea editable.
Ahora, la propuesta de solución actual es que si uno quiere alterar esta lista de evidencias para un caso/evento se debe acceder al evento/caso y eliminar individualmente las mismas en el frontend (o realizar delete sobre el backend de cada evidencia), y para subir en el backend subir los archivos de a 1 asignando los mismos al caso/evento actual (o el edit multipart con los files como funciona hasta el momento el frontend)
