### ISSUE TITLE
Bug en redes en ordenamiento por entidad

### ISSUE THREAD

**Issue by fran1999** [CERTUNLP/ngen#112]
En Redes el ordenamiento por entidad está invertido, el ordenamiento ascendente ordena de manera descendente y viceversa para el descendente
Cuando la consulta al backend se realiza de forma ascendente se ve ordenado descendente: 
![image](https://github.com/CERTUNLP/ngen/assets/62036079/cff73965-9948-4ee7-97c0-69f628962d11)

**Comment by mateodurante** [comment]
Se arregla en #117 , faltaba el ordenamiento por nombre de entidad, estaba puesto en entidad sola (id), hay que cambiarlo en el frontend para `network_entity__name`
