### ISSUE TITLE
Faltan ordenamientos en componentes

### ISSUE THREAD

**Issue by fran1999** [CERTUNLP/ngen#113]
En taxonomia falta el ordenamiento por cantidad de eventos .
En Plantilla falta ordenar por fuente.

**Comment by mateodurante** [comment]
@fran1999  se agregaron los campos mencionados en #116 , fijate que ademas se cambia el nombre de una variable de `template` de `matching_events_without_case` a `matching_events_without_case_count`, para agregarlo al frontend.
