### ISSUE TITLE
Error al editar el recurso afectado de un evento 

### ISSUE THREAD

**Issue by fran1999** [CERTUNLP/ngen#114]
Cuando se edita un evento, y se cambia el recurso afectado por un valor que no esta en la lista de artefactos, el backend responde con un error 500
![image](https://github.com/CERTUNLP/ngen/assets/62036079/deca4711-de52-4ab2-b03d-c1eacc33f328)

**Comment by mateodurante** [comment]
Posiblemente sea resuelto en #111
