### ISSUE TITLE
Campos obligatorios al crear un reporte

### ISSUE THREAD

**Issue by ucabrera** [CERTUNLP/ngen#122]
Cuando se crea un reporte, todos los campos son obligatorios, pero en la interfaz solo aparecen como obligatorios:
- taxonomía
- idioma
- problema

Se adjunta captura donde la verificación está en blanco y no se puede guardar
![image](https://github.com/CERTUNLP/ngen/assets/668847/0d8ff918-bfed-4e02-8c29-b34d95c6f75d)

Por otro lado, estaría bueno que en vez de informar:  "El reporte no se pudo crear." 
![image](https://github.com/CERTUNLP/ngen/assets/668847/96221be0-f697-43c1-af7e-525c7633d02d)
Aparezca el listado de todos lo problemas que hay y uno no tenga que verificar a mano cual fue la respuesta del servidor.

**Comment by mateodurante** [comment]
Fixed on 886095e8dd7277a082e53dbc69018faffe31b774
