### ISSUE TITLE
Mejoras frontend

### ISSUE THREAD

**Issue by gabisuarez** [CERTUNLP/ngen#144]
A continuación se describen un conjunto sugerencias para mejorar la estructura del código del frontend: 

1. Dentro del directorio componentes hay 3 archivos sueltos: CallbackByName.js, CallbackByType.js, LetterFormat.js.
Podría quedar más prolijo si sólo se contara con los directorios de los componentes. Se podría repensar dónde ubicar los archivos sueltos. 

2. Dentro del dIrectorio Utils: se encuentra el directorio validators y por otro lado un archivo validators.js. Se podría unificar, que el archivo quede dentro del directorio. 

3. Componente button: La idea sería dejar definidos botones genéricos que se usan en la app como por ejemplo ActiveButton.js. El archivo ViewFiles.js tiene lógica específica de evidencias. Podría ir dentro de ese componente. 

4. Dentro de las vistas, debería asegurarse que cada componente cuente con la siguiente estructura: CreateComponent.js
EditComponent.js, ListComponent.js y Directorio “components” (donde se almacenan todos los componentes extra definidos para reutilizar o simplificar componentes macro). Eventos y casos no cumplen esta estructura (usar “entity” de referencia). 
Tanto evento como casos tienen los css dentro de su carpeta componente. Ver si es posible ponerlo en el index.scss .

5. En diferentes archivos se encuentran comentarios en español o en inglés para explicar la lógica del código. Se podría estandarizar y definir un idioma. Esto se puede observar por ejemplo en: 
Components → Button → ViewFiles.js
Views → case → ListCase.js

**Comment by mateodurante** [comment]
Se esta trabajando en la limpieza y refactorización de código. Se aceptan PRs.
El idioma estandar para el proyecto es el ingles.
