### ISSUE TITLE
Feeds

### ISSUE THREAD

**Issue by rubiodamian** [CERTUNLP/ngen#16]
el objeto Feed es solo un label.
deberia tener un usuario asignado ya que actualmente se crean usuarios para cada feed y no queda bien

**Comment by mateodurante** [comment]
This overly complicates the task of configuring tools or automated machines for sending information sources that aggregate a set of feeds like IntelMQ, plus the logic in the model where a user must be related to the possible feeds from which they can report. Users are currently role/permission encapsulators per endpoint; we will not be implementing logic for object-level actions at the moment.
