### ISSUE TITLE
No cargan los datos en la sección Métricas al ingresar

### ISSUE THREAD

**Issue by pvenosa** [CERTUNLP/ngen#72]
Cuando se ingresa al sistema no carga de una el contenido de la sección Métricas...luego de clickear en alguna otra opción si se vuelve a la sección en métricas desde el menú si carga

![image](https://github.com/CERTUNLP/ngen/assets/22666141/c7d1bebd-4274-4daf-bd72-435d3a22d79d)

**Comment by mateodurante** [comment]
Thanks for report.

Fixed on CERTUNLP/ngen-frontend#12
