### ISSUE TITLE
Error en buscador de reportes

### ISSUE THREAD

**Issue by AgusEchaniz** [CERTUNLP/ngen#86]
Si busco algún tipo de reporte no solo no lo busca si no que además se traba y me inhabilita. Tengo que recargar la página para que vuelva a funcionar. 

![image](https://github.com/CERTUNLP/ngen/assets/668847/14936273-f45d-44f3-a15d-63cbe35e5008)

path: /reports

**Comment by fran1999** [comment]
El error de que la página quede inhabilitada esta solucionado pero falta implementar la busqueda de reportes por taxonomia en backend
