### ISSUE TITLE
Propuesta de mejora en los criterios de ordenamiento de los listados

### ISSUE THREAD

**Issue by AgusEchaniz** [CERTUNLP/ngen#87]
1. En Eventos:
> 1.a. Orden predeterminado: por fecha descendente.

2. En Casos:
> 2.a. Orden predeterminado: por fecha descendente.

3. En Entidades:
> 3.a. Ordenar por nombre.
> 3.b. Orden predeterminado: por nombre ascendente.

4. En Redes:
> 4.a. Ordenar por entidad.
> 4.b. Orden predeterminado: por entidad ascendente.

5. En Contactos:
> 5.a. Ordenar por nombre.
> 5.b. Orden predeterminado: por nombre ascendente.

6. En Reporte:
> 6.a. Ordenar por taxonomía.
> 6.b. Orden predeterminado: por taxonomía ascendente.

7. En Fuentes:
> 7.a. Orden predeterminado: por nombre ascendente.

8. En Prioridades:
> 8.a. Orden predeterminado: por nombre ascendente.

9. En Taxonomía:
> 9.a. Ordenar por cantidad de eventos también. 
> 9.b. Orden predeterminado: por nombre ascendente.

10. En Plantilla:
> 10.a. Ordenar por taxonomía o fuente.

**Comment by fran1999** [comment]
Los Ordenamientos ya se encuentran implementados en frontend a excepción del Ordenamiento por cantidad de eventos en taxonomia. El backend no trae la cantidad de eventos si no la cantidad de reportes asociados , no se considero prioritario hacer el ordenamiento por cantidad de reportes.
