### ISSUE TITLE
Error en la validación de fecha en la creación de un evento

### ISSUE THREAD

**Issue by AgusEchaniz** [CERTUNLP/ngen#89]
Al crear un evento me permite poner una fecha posterior a la actual.

![problema 7](https://github.com/CERTUNLP/ngen/assets/62100392/84f56fa3-8d1f-4035-807c-00c460526ffe)

**Comment by mateodurante** [comment]
Gracias por el reporte, queda que el frontend agregue la validación de la fecha y mensaje de error
