### ISSUE TITLE
Error en las fechas de los casos

### ISSUE THREAD

**Issue by AgusEchaniz** [CERTUNLP/ngen#92]
1. Al crear un caso me permite utilizar fechas posteriores a la actual en los tres campos correspondientes a fechas. 
2. No guarda las fechas de atención y de resolución, tanto al crearlo como al editarlo. 
3. En la fecha de creación el horario no aparece en GMT -3.

![problema 8 2](https://github.com/CERTUNLP/ngen/assets/62100392/0ea450fb-dc72-4945-8b50-f2f0c87e91c9)

**Comment by mateodurante** [comment]
El campo `Fecha` sera ser eliminado porque es redundante.

1. En `fecha` si, pero el resto no debería ocurrir ya que son valores automáticos no asignables por el usuario. Tal vez es debido al timezone que tenes y que se te muestran en UTC?
2. Los campos `creacion`, `modificacion`, `atencion` y `resolucion` se actualizan correctamente en base a cada una de sus funcionalidades. Podrías ser mas especifica en los pasos a seguir para encontrar el bug?
3. Es cierto, es un feature para resolver por el frontend que se muestren las fechas en el horario del navegador o el elegido por el usuario.

Gracias!

**Comment by gabisuarez** [comment]
1. "Al crear un caso me permite utilizar fechas posteriores a la actual en los tres campos correspondientes a fechas": las fechas de atención y resolución han sido eliminadas en la pantalla de creación. La fecha de inicio de gestión se setea por defecto en la fecha actual o en caso de ser editada por el usuario se valida que sea igual o anterior a la actual. 

3. "No guarda las fechas de atención y de resolución, tanto al crearlo como al editarlo":  las fechas de atención y resolución han sido eliminadas en la pantalla de creación y edición. 

5. "En la fecha de creación el horario no aparece en GMT -3": esta petición lo tendremos en cuenta como mejora en una siguiente versión. 

Gracias
