### ISSUE TITLE
Quitar fecha de ocurrencia de Casos del modelo 

### ISSUE THREAD

**Issue by gabisuarez** [CERTUNLP/ngen#94]
Quitar fecha de ocurrencia de Casos del modelo de backend. Se concluyó que no es un campo necesario.

**Comment by mateodurante** [comment]
Los casos permanecerán con la el campo `date` que representa la fecha de ocurrencia. En el frontend por defecto debe ser cargado con la fecha actual, modificable y si se envía vacío a la api se utiliza la fecha actual.
