### ISSUE TITLE
bug al agregar un recurso afectado en un evento 

### ISSUE THREAD

**Issue by fran1999** [CERTUNLP/ngen#97]
cuando agrego el dominio "unlp.edu.info.ar" como recurso afectado, no se guarda como artefacto y el validador del backend lo toma como valido
![evento-recurso_afectado](https://github.com/CERTUNLP/ngen/assets/62036079/ac629da3-db96-4048-97a9-55ed9799455e)

**Comment by mateodurante** [comment]
No se encontró problema en el issue, por favor volver a cargarlo de forma mas descriptiva si se vuelve a encontrar.
